/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * the-recipe-db API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
export interface ConfirmImportRequest {
  recipes?: ConfirmedRecipe[];
}

export interface ConfirmedRecipe {
  recipeName?: string;
  pageNumber?: number;
  ingredient?: string;
  keep?: boolean;
}

export interface CreateCookbookRequest {
  title?: string;
  author?: string;
}

export interface MergeIngredientsRequest {
  targetId?: Uuid;
  sourceIds?: string[];
}

/**
 * @pattern [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}
 */
export type Uuid = string;

export interface UpdateIngredientRequest {
  name?: string;
  disambiguations?: string[];
  availableMonths?: number[];
}

export type GetApiCookbooksParams = {
q?: string;
};

export type PostApiCookbooksIdCoverBody = {
  file?: Blob;
};

export type PostApiCookbooksIdIndexPagesBody = {
  files?: Blob[];
};

export type GetApiIngredientsParams = {
availableNow?: boolean;
cursor?: Uuid;
hasDisambiguations?: boolean;
limit?: number;
minRecipeCount?: number;
q?: string;
};

export type GetApiIngredientsIdRecipesParams = {
cookbookId?: Uuid;
cursor?: string;
limit?: number;
q?: string;
};

export type GetApiRecipesParams = {
availableNow?: boolean;
cookbookId?: Uuid;
cursor?: string;
ingredient?: string;
limit?: number;
q?: string;
};

/**
 * @summary List Cookbooks
 */
export type getApiCookbooksResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiCookbooksResponseSuccess = (getApiCookbooksResponse200) & {
  headers: Headers;
};
;

export type getApiCookbooksResponse = (getApiCookbooksResponseSuccess)

export const getGetApiCookbooksUrl = (params?: GetApiCookbooksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/cookbooks?${stringifiedParams}` : `/api/cookbooks`
}

export const getApiCookbooks = async (params?: GetApiCookbooksParams, options?: RequestInit): Promise<getApiCookbooksResponse> => {
  
  const res = await fetch(getGetApiCookbooksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCookbooksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCookbooksResponse
}



/**
 * @summary Create Cookbook
 */
export type postApiCookbooksResponse200 = {
  data: unknown
  status: 200
}

export type postApiCookbooksResponse400 = {
  data: void
  status: 400
}
    
export type postApiCookbooksResponseSuccess = (postApiCookbooksResponse200) & {
  headers: Headers;
};
export type postApiCookbooksResponseError = (postApiCookbooksResponse400) & {
  headers: Headers;
};

export type postApiCookbooksResponse = (postApiCookbooksResponseSuccess | postApiCookbooksResponseError)

export const getPostApiCookbooksUrl = () => {


  

  return `/api/cookbooks`
}

export const postApiCookbooks = async (createCookbookRequest: CreateCookbookRequest, options?: RequestInit): Promise<postApiCookbooksResponse> => {
  
  const res = await fetch(getPostApiCookbooksUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCookbookRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiCookbooksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCookbooksResponse
}



/**
 * @summary Get Cookbook
 */
export type getApiCookbooksIdResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiCookbooksIdResponseSuccess = (getApiCookbooksIdResponse200) & {
  headers: Headers;
};
;

export type getApiCookbooksIdResponse = (getApiCookbooksIdResponseSuccess)

export const getGetApiCookbooksIdUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}`
}

export const getApiCookbooksId = async (id: Uuid, options?: RequestInit): Promise<getApiCookbooksIdResponse> => {
  
  const res = await fetch(getGetApiCookbooksIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCookbooksIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCookbooksIdResponse
}



/**
 * @summary Delete Cookbook
 */
export type deleteApiCookbooksIdResponse200 = {
  data: unknown
  status: 200
}
    
export type deleteApiCookbooksIdResponseSuccess = (deleteApiCookbooksIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiCookbooksIdResponse = (deleteApiCookbooksIdResponseSuccess)

export const getDeleteApiCookbooksIdUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}`
}

export const deleteApiCookbooksId = async (id: Uuid, options?: RequestInit): Promise<deleteApiCookbooksIdResponse> => {
  
  const res = await fetch(getDeleteApiCookbooksIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiCookbooksIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiCookbooksIdResponse
}



/**
 * @summary Confirm Import
 */
export type postApiCookbooksIdConfirmResponse200 = {
  data: unknown
  status: 200
}

export type postApiCookbooksIdConfirmResponse400 = {
  data: void
  status: 400
}
    
export type postApiCookbooksIdConfirmResponseSuccess = (postApiCookbooksIdConfirmResponse200) & {
  headers: Headers;
};
export type postApiCookbooksIdConfirmResponseError = (postApiCookbooksIdConfirmResponse400) & {
  headers: Headers;
};

export type postApiCookbooksIdConfirmResponse = (postApiCookbooksIdConfirmResponseSuccess | postApiCookbooksIdConfirmResponseError)

export const getPostApiCookbooksIdConfirmUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}/confirm`
}

export const postApiCookbooksIdConfirm = async (id: Uuid,
    confirmImportRequest: ConfirmImportRequest, options?: RequestInit): Promise<postApiCookbooksIdConfirmResponse> => {
  
  const res = await fetch(getPostApiCookbooksIdConfirmUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      confirmImportRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiCookbooksIdConfirmResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCookbooksIdConfirmResponse
}



/**
 * @summary Upload Cover
 */
export type postApiCookbooksIdCoverResponse200 = {
  data: unknown
  status: 200
}
    
export type postApiCookbooksIdCoverResponseSuccess = (postApiCookbooksIdCoverResponse200) & {
  headers: Headers;
};
;

export type postApiCookbooksIdCoverResponse = (postApiCookbooksIdCoverResponseSuccess)

export const getPostApiCookbooksIdCoverUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}/cover`
}

export const postApiCookbooksIdCover = async (id: Uuid,
    postApiCookbooksIdCoverBody: PostApiCookbooksIdCoverBody, options?: RequestInit): Promise<postApiCookbooksIdCoverResponse> => {
    const formData = new FormData();
if(postApiCookbooksIdCoverBody.file !== undefined) {
 formData.append(`file`, postApiCookbooksIdCoverBody.file)
 }

  const res = await fetch(getPostApiCookbooksIdCoverUrl(id),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiCookbooksIdCoverResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCookbooksIdCoverResponse
}



/**
 * @summary Get Cover
 */
export type getApiCookbooksIdCoverResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getApiCookbooksIdCoverResponseError = (getApiCookbooksIdCoverResponseDefault) & {
  headers: Headers;
};

export type getApiCookbooksIdCoverResponse = (getApiCookbooksIdCoverResponseError)

export const getGetApiCookbooksIdCoverUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}/cover`
}

export const getApiCookbooksIdCover = async (id: Uuid, options?: RequestInit): Promise<getApiCookbooksIdCoverResponse> => {
  
  const res = await fetch(getGetApiCookbooksIdCoverUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCookbooksIdCoverResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCookbooksIdCoverResponse
}



/**
 * @summary Upload Index Pages
 */
export type postApiCookbooksIdIndexPagesResponse200 = {
  data: unknown
  status: 200
}

export type postApiCookbooksIdIndexPagesResponse400 = {
  data: void
  status: 400
}
    
export type postApiCookbooksIdIndexPagesResponseSuccess = (postApiCookbooksIdIndexPagesResponse200) & {
  headers: Headers;
};
export type postApiCookbooksIdIndexPagesResponseError = (postApiCookbooksIdIndexPagesResponse400) & {
  headers: Headers;
};

export type postApiCookbooksIdIndexPagesResponse = (postApiCookbooksIdIndexPagesResponseSuccess | postApiCookbooksIdIndexPagesResponseError)

export const getPostApiCookbooksIdIndexPagesUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}/index-pages`
}

export const postApiCookbooksIdIndexPages = async (id: Uuid,
    postApiCookbooksIdIndexPagesBody: PostApiCookbooksIdIndexPagesBody, options?: RequestInit): Promise<postApiCookbooksIdIndexPagesResponse> => {
    const formData = new FormData();
if(postApiCookbooksIdIndexPagesBody.files !== undefined) {
 postApiCookbooksIdIndexPagesBody.files.forEach(value => formData.append(`files`, value));
 }

  const res = await fetch(getPostApiCookbooksIdIndexPagesUrl(id),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiCookbooksIdIndexPagesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCookbooksIdIndexPagesResponse
}



/**
 * @summary Start Ocr Processing
 */
export type postApiCookbooksIdOcrStartResponse200 = {
  data: unknown
  status: 200
}
    
export type postApiCookbooksIdOcrStartResponseSuccess = (postApiCookbooksIdOcrStartResponse200) & {
  headers: Headers;
};
;

export type postApiCookbooksIdOcrStartResponse = (postApiCookbooksIdOcrStartResponseSuccess)

export const getPostApiCookbooksIdOcrStartUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}/ocr/start`
}

export const postApiCookbooksIdOcrStart = async (id: Uuid, options?: RequestInit): Promise<postApiCookbooksIdOcrStartResponse> => {
  
  const res = await fetch(getPostApiCookbooksIdOcrStartUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiCookbooksIdOcrStartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiCookbooksIdOcrStartResponse
}



/**
 * @summary Get Cookbook Recipes
 */
export type getApiCookbooksIdRecipesResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiCookbooksIdRecipesResponseSuccess = (getApiCookbooksIdRecipesResponse200) & {
  headers: Headers;
};
;

export type getApiCookbooksIdRecipesResponse = (getApiCookbooksIdRecipesResponseSuccess)

export const getGetApiCookbooksIdRecipesUrl = (id: Uuid,) => {


  

  return `/api/cookbooks/${id}/recipes`
}

export const getApiCookbooksIdRecipes = async (id: Uuid, options?: RequestInit): Promise<getApiCookbooksIdRecipesResponse> => {
  
  const res = await fetch(getGetApiCookbooksIdRecipesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCookbooksIdRecipesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCookbooksIdRecipesResponse
}



/**
 * @summary List Ingredients
 */
export type getApiIngredientsResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiIngredientsResponseSuccess = (getApiIngredientsResponse200) & {
  headers: Headers;
};
;

export type getApiIngredientsResponse = (getApiIngredientsResponseSuccess)

export const getGetApiIngredientsUrl = (params?: GetApiIngredientsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ingredients?${stringifiedParams}` : `/api/ingredients`
}

export const getApiIngredients = async (params?: GetApiIngredientsParams, options?: RequestInit): Promise<getApiIngredientsResponse> => {
  
  const res = await fetch(getGetApiIngredientsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiIngredientsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiIngredientsResponse
}



/**
 * @summary Merge Ingredients
 */
export type postApiIngredientsMergeResponse200 = {
  data: unknown
  status: 200
}

export type postApiIngredientsMergeResponse400 = {
  data: void
  status: 400
}
    
export type postApiIngredientsMergeResponseSuccess = (postApiIngredientsMergeResponse200) & {
  headers: Headers;
};
export type postApiIngredientsMergeResponseError = (postApiIngredientsMergeResponse400) & {
  headers: Headers;
};

export type postApiIngredientsMergeResponse = (postApiIngredientsMergeResponseSuccess | postApiIngredientsMergeResponseError)

export const getPostApiIngredientsMergeUrl = () => {


  

  return `/api/ingredients/merge`
}

export const postApiIngredientsMerge = async (mergeIngredientsRequest: MergeIngredientsRequest, options?: RequestInit): Promise<postApiIngredientsMergeResponse> => {
  
  const res = await fetch(getPostApiIngredientsMergeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mergeIngredientsRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiIngredientsMergeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiIngredientsMergeResponse
}



/**
 * @summary Update Ingredient
 */
export type putApiIngredientsIdResponse200 = {
  data: unknown
  status: 200
}

export type putApiIngredientsIdResponse400 = {
  data: void
  status: 400
}
    
export type putApiIngredientsIdResponseSuccess = (putApiIngredientsIdResponse200) & {
  headers: Headers;
};
export type putApiIngredientsIdResponseError = (putApiIngredientsIdResponse400) & {
  headers: Headers;
};

export type putApiIngredientsIdResponse = (putApiIngredientsIdResponseSuccess | putApiIngredientsIdResponseError)

export const getPutApiIngredientsIdUrl = (id: Uuid,) => {


  

  return `/api/ingredients/${id}`
}

export const putApiIngredientsId = async (id: Uuid,
    updateIngredientRequest: UpdateIngredientRequest, options?: RequestInit): Promise<putApiIngredientsIdResponse> => {
  
  const res = await fetch(getPutApiIngredientsIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateIngredientRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiIngredientsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiIngredientsIdResponse
}



/**
 * @summary Get Ingredient
 */
export type getApiIngredientsIdResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiIngredientsIdResponseSuccess = (getApiIngredientsIdResponse200) & {
  headers: Headers;
};
;

export type getApiIngredientsIdResponse = (getApiIngredientsIdResponseSuccess)

export const getGetApiIngredientsIdUrl = (id: Uuid,) => {


  

  return `/api/ingredients/${id}`
}

export const getApiIngredientsId = async (id: Uuid, options?: RequestInit): Promise<getApiIngredientsIdResponse> => {
  
  const res = await fetch(getGetApiIngredientsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiIngredientsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiIngredientsIdResponse
}



/**
 * @summary Delete Ingredient
 */
export type deleteApiIngredientsIdResponse200 = {
  data: unknown
  status: 200
}
    
export type deleteApiIngredientsIdResponseSuccess = (deleteApiIngredientsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiIngredientsIdResponse = (deleteApiIngredientsIdResponseSuccess)

export const getDeleteApiIngredientsIdUrl = (id: Uuid,) => {


  

  return `/api/ingredients/${id}`
}

export const deleteApiIngredientsId = async (id: Uuid, options?: RequestInit): Promise<deleteApiIngredientsIdResponse> => {
  
  const res = await fetch(getDeleteApiIngredientsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiIngredientsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiIngredientsIdResponse
}



/**
 * @summary Get Ingredient Recipes
 */
export type getApiIngredientsIdRecipesResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiIngredientsIdRecipesResponseSuccess = (getApiIngredientsIdRecipesResponse200) & {
  headers: Headers;
};
;

export type getApiIngredientsIdRecipesResponse = (getApiIngredientsIdRecipesResponseSuccess)

export const getGetApiIngredientsIdRecipesUrl = (id: Uuid,
    params?: GetApiIngredientsIdRecipesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ingredients/${id}/recipes?${stringifiedParams}` : `/api/ingredients/${id}/recipes`
}

export const getApiIngredientsIdRecipes = async (id: Uuid,
    params?: GetApiIngredientsIdRecipesParams, options?: RequestInit): Promise<getApiIngredientsIdRecipesResponse> => {
  
  const res = await fetch(getGetApiIngredientsIdRecipesUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiIngredientsIdRecipesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiIngredientsIdRecipesResponse
}



/**
 * @summary List Recipes
 */
export type getApiRecipesResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiRecipesResponseSuccess = (getApiRecipesResponse200) & {
  headers: Headers;
};
;

export type getApiRecipesResponse = (getApiRecipesResponseSuccess)

export const getGetApiRecipesUrl = (params?: GetApiRecipesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/recipes?${stringifiedParams}` : `/api/recipes`
}

export const getApiRecipes = async (params?: GetApiRecipesParams, options?: RequestInit): Promise<getApiRecipesResponse> => {
  
  const res = await fetch(getGetApiRecipesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiRecipesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiRecipesResponse
}



/**
 * @summary Get Recipe
 */
export type getApiRecipesIdResponse200 = {
  data: unknown
  status: 200
}
    
export type getApiRecipesIdResponseSuccess = (getApiRecipesIdResponse200) & {
  headers: Headers;
};
;

export type getApiRecipesIdResponse = (getApiRecipesIdResponseSuccess)

export const getGetApiRecipesIdUrl = (id: Uuid,) => {


  

  return `/api/recipes/${id}`
}

export const getApiRecipesId = async (id: Uuid, options?: RequestInit): Promise<getApiRecipesIdResponse> => {
  
  const res = await fetch(getGetApiRecipesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiRecipesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiRecipesIdResponse
}
